services:

  postgres-db:
    image: postgres:18.4
    restart: always
    shm_size: 128mb
    ports:
      - "5432:5432"
    env_file: .env
    volumes:
      - city-report-data:/var/lib/postgresql
      - ../db/seed-db.sql:/docker-entrypoint-initdb.d/seed-db.sql
    networks:
      - city-report-net

  demo-report-images-init:
    image: alpine:3.22.4
    command: >
      sh -c '
        set -e
        if [ ! -e /mnt/report-images/.initialized ]; then
          cp -a /seed/. /mnt/report-images/
          touch /mnt/report-images/.initialized
        fi
      '
    volumes:
      - report-images:/mnt/report-images:z
      - ./demo-report-images:/seed:ro
    restart: "no"

  user-api:
    build:
      context: .
      dockerfile: docker/user-api.Dockerfile
    ports:
      - "5000:5000"
    restart: always
    env_file: .env
    environment:
      API_BASE_URL: ${API_BASE_URL}
      # psycopg specific env variables
      PGHOST: postgres-db
      PGPORT: 5432
      PGDATABASE: ${POSTGRES_DB}
      PGUSER: ${POSTGRES_USER}
      PGPASSWORD: ${POSTGRES_PASSWORD}
    depends_on:
      postgres-db:
        condition: service_started
      demo-report-images-init:
        condition: service_completed_successfully
    volumes:
      - report-images:/mnt/report-images:z
      # These mounts are development only, remove on production
      - ./user_api:/app/user_api
      - ./db_repository:/app/db_repository:z
    networks:
      - city-report-net

  admin-dashboard:
    build:
      context: .
      dockerfile: docker/admin-dashboard.Dockerfile
    ports:
      - "8501:8501"
    restart: always
    env_file: .env
    environment:
      # psycopg specific env variables
      PGHOST: postgres-db
      PGPORT: 5432
      PGDATABASE: ${POSTGRES_DB}
      PGUSER: ${POSTGRES_USER}
      PGPASSWORD: ${POSTGRES_PASSWORD}
    depends_on:
      postgres-db:
        condition: service_started
      demo-report-images-init:
        condition: service_completed_successfully
    volumes:
      - report-images:/mnt/report-images:z
      # These mounts are development only, remove on production
      - ./admin_dashboard:/app/admin_dashboard
      - ./db_repository:/app/db_repository:z
    networks:
      - city-report-net

volumes:
  city-report-data:
  report-images:

networks:
  city-report-net: {}
  