services:

  postgres-db:
    image: postgres:18.4
    restart: always
    shm_size: 128mb
    ports:
      - "5432:5432"
    env_file: .env
    volumes:
      - city-report-data:/var/lib/postgresql
      - ../db/seed-db.sql:/docker-entrypoint-initdb.d/seed-db.sql
    networks:
      - city-report-net

  user-api:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "5000:5000"
    restart: always
    env_file: .env
    environment:
      PGHOST: postgres-db
      PGPORT: 5432
      PGDATABASE: ${POSTGRES_DB}
      PGUSER: ${POSTGRES_USER}
      PGPASSWORD: ${POSTGRES_PASSWORD}
    depends_on:
      - postgres-db
    networks:
      - city-report-net

volumes:
  city-report-data:   

networks:
  city-report-net: {}
  